databases:
  - name: visadb
    plan: free
    databaseName: visadb
    user: iaz

services:
  - type: web
    plan: free
    name: url_shortener_take_home
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "pipenv run gunicorn url_shortener_take_home.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: PIPENV_YES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: visadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
