# Generated by Django 4.2.3 on 2023-07-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="pin",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="url",
            name="hashed_url",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
